export const SET_AUTH_STATE = 'app/user/SET_AUTH_STATE';
export const SET_HFN_PROFILE = 'app/user/SET_HFN_PROFILE';
export const CLEAR_HFN_PROFILE = 'app/user/CLEAR_HFN_PROFILE';
export const SET_TAKEN_INTODUCTORY_SITTINGS =
    'app/user/SET_TAKEN_INTODUCTORY_SITTINGS';
export const SET_INTODUCTORY_SITTINGS_COMPLETION_DETAIL_ENQUIRY_FILLED_STATUS =
    'app/user/SET_INTODUCTORY_SITTINGS_COMPLETION_DETAIL_ENQUIRY_FILLED_STATUS';
export const SET_PLAY_GUIDED_RELAXATION_AUDIO =
    'app/user/SET_PLAY_GUIDED_RELAXATION_AUDIO';
export const SET_WEEKLY_INSPIRATION_NOTIFICATION_SUBSCRIPTION_STATUS =
    'app/user/SET_WEEKLY_INSPIRATION_NOTIFICATION_SUBSCRIPTION_STATUS';
export const SET_USER_PREFERENCE_SITTINGS =
    'app/user/SET_USER_PREFERENCE_SITTINGS';
export const SET_AGE_CONSENT_POPUP_VISIBILITY =
    'app/user/SET_AGE_CONSENT_POPUP_VISIBILITY';
export const SET_MEDITATION_REMINDERS_SETTINGS =
    'app/user/SET_MEDITATION_REMINDERS_SETTINGS';
export const SET_REMIND_FOR_NEXT_SESSION_BUTTON_VISIBILITY =
    'app/user/SET_REMIND_FOR_NEXT_SESSION_BUTTON_VISIBILITY';
export const SET_COUNT_OF_SITTINGS_TAKEN =
    'app/user/SET_COUNT_OF_SITTINGS_TAKEN';
export const SET_COUNT_OF_SITTINGS_GIVEN_THROUGH_HEARTSAPP =
    'app/user/SET_COUNT_OF_SITTINGS_GIVEN_THROUGH_HEARTSAPP';
export const SET_COUNT_OF_SITTINGS_GIVEN_OFFLINE =
    'app/user/SET_COUNT_OF_SITTINGS_GIVEN_OFFLINE';
