export const NEWBIE_MASTER_CLASS_CONTAINER_OPTIONS = {
    INTRODUCTION_TO_HFN_MEDITATION_CONTAINER:
        'INTRODUCTION_TO_HFN_MEDITATION_CONTAINER',
    MASTER_CLASSES_PROGRESS_SUMMARY_CONTAINER:
        'MASTER_CLASSES_PROGRESS_SUMMARY_CONTAINER',
    MASTER_CLASS_CONTAINER: 'MASTER_CLASS_CONTAINER',
    MASTER_CLASS_INFO_CONTAINER: 'MASTER_CLASS_INFO_CONTAINER',
    MASTER_CLASS_COMPLETION_CONTAINER: 'MASTER_CLASS_COMPLETION_CONTAINER',
};
