export const SET_STATE = 'app/seekerMeditation/SET_STATE';
export const SET_MEDITATION_SESSION_CONFIGURATION =
    'app/seekerMeditation/SET_MEDITATION_SESSION_CONFIGURATION';
export const SET_ELAPSED_MEDITATION_DURATION =
    'app/seekerMeditation/SET_ELAPSED_MEDITATION_DURATION';
export const SET_MEDITATION_CANCEL_BUTTON_ENABLE =
    'app/seekerMeditation/SET_MEDITATION_CANCEL_BUTTON_ENABLE';
export const SET_REQUEST_FOR_MEDITATION_SESSION =
    'app/seekerMeditation/SET_REQUEST_FOR_MEDITATION_SESSION';
export const SET_MAX_WAITING_END_TIME_BEFORE_SESSION_START =
    'app/seekerMeditation/SET_MAX_WAITING_END_TIME_BEFORE_SESSION_START';
