export const LOAD_BOOKS = 'LOAD_BOOKS';
export const SET_BOOKS_LIST_LOADING = 'SET_BOOKS_LIST_LOADING';
export const SET_BOOKS_LIST_LOADING_MORE = 'SET_BOOKS_LIST_LOADING_MORE';
export const LOAD_MORE_BOOKS = 'LOAD_MORE_BOOKS';
export const BOOKS_LIST_LOADING_FAILED = 'BOOKS_LIST_LOADING_FAILED';

export const LOAD_WHISPERS_COLLECTIONS = 'LOAD_WHISPERS_COLLECTIONS';
export const SET_WHISPERS_COLLECTIONS_LIST_LOADING = 'SET_WHISPERS_COLLECTIONS_LIST_LOADING';
export const SET_WHISPERS_COLLECTIONS_LIST_LOADING_MORE = 'SET_WHISPERS_COLLECTIONS_LIST_LOADING_MORE';
export const LOAD_MORE_WHISPERS_COLLECTIONS = 'LOAD_MORE_WHISPERS_COLLECTIONS';
export const WHISPERS_COLLECTIONS_LIST_LOADING_FAILED = 'WHISPERS_COLLECTIONS_LIST_LOADING_FAILED';

export const EXIT_APP = 'EXIT_APP';
export const SET_NAV_BAR = 'SET_NAV_BAR';
export const GO_BACK = 'GO_BACK';
export const SET_HARDWARE_BACK_BUTTON_ACTION = 'SET_HARDWARE_BACK_BUTTON_ACTION';

export const OPEN_COLLECTION_DOCUMENTS_SUGGESTIONS_SCREEN = 'OPEN_COLLECTION_DOCUMENTS_SUGGESTIONS_SCREEN';
export const CHANGE_COLLECTION_DOCUMENTS_SEARCH_TEXT = 'CHANGE_COLLECTION_DOCUMENTS_SEARCH_TEXT';
export const SET_COLLECTION_DOCUMENTS_SUGGESTIONS_LOADING = 'SET_COLLECTION_DOCUMENTS_SUGGESTIONS_LOADING';
export const COLLECTION_DOCUMENTS_SUGGESTIONS_LOADING_FAILED = 'COLLECTION_DOCUMENTS_SUGGESTIONS_LOADING_FAILED';
export const LOAD_COLLECTION_DOCUMENTS_SUGGESTIONS = 'LOAD_COLLECTION_DOCUMENTS_SUGGESTIONS';

export const LOAD_COLLECTION_DETAIL = 'LOAD_COLLECTION_DETAIL';
export const SET_COLLECTION_DETAIL_LOADING = 'SET_COLLECTION_DETAIL_LOADING';
export const SET_COLLECTION_DETAIL_LOADING_MORE = 'SET_COLLECTION_DETAIL_LOADING_MORE';
export const LOAD_MORE_COLLECTION_DETAIL = 'LOAD_MORE_COLLECTION_DETAIL';
export const COLLECTION_DETAIL_LOADING_FAILED = 'COLLECTION_DETAIL_LOADING_FAILED';
export const SET_COLLECTION_DETAIL_ID = 'SET_COLLECTION_DETAIL_ID';
export const SET_COLLECTION_DETAIL = 'SET_COLLECTION_DETAIL';

export const LOAD_DOCUMENT_DETAIL = 'LOAD_DOCUMENT_DETAIL';
export const SET_DOCUMENT_DETAIL_LOADING = 'SET_DOCUMENT_DETAIL_LOADING';
export const SET_DOCUMENT_DETAIL_LOADING_MORE = 'SET_DOCUMENT_DETAIL_LOADING_MORE';
export const LOAD_MORE_DOCUMENT_DETAIL = 'LOAD_MORE_DOCUMENT_DETAIL';
export const DOCUMENT_DETAIL_LOADING_FAILED = 'DOCUMENT_DETAIL_LOADING_FAILED';
export const SET_DOCUMENT_DETAIL_ID = 'SET_DOCUMENT_DETAIL_ID';

export const SET_FONT_THEME = 'SET_FONT_THEME';
export const SET_SIZE_THEME = 'SET_SIZE_THEME';
export const SET_COLOR_THEME = 'SET_COLOR_THEME';

export const OPEN_THEME_SETTINGS_MODAL = 'OPEN_THEME_SETTINGS_MODAL';
export const CLOSE_THEME_SETTINGS_MODAL = 'CLOSE_THEME_SETTINGS_MODAL';

export const LOAD_SEARCH_RESULTS = 'LOAD_SEARCH_RESULTS';
export const SET_SEARCH_RESULTS_LIST_LOADING = 'SET_SEARCH_RESULTS_LIST_LOADING';
export const SET_SEARCH_RESULTS_LIST_LOADING_MORE = 'SET_SEARCH_RESULTS_LIST_LOADING_MORE';
export const LOAD_MORE_SEARCH_RESULTS = 'LOAD_MORE_SEARCH_RESULTS';
export const SEARCH_RESULT_LIST_LOADING_FAILED = 'SEARCH_RESULT_LIST_LOADING_FAILED';

export const ADD_SEARCH_KEYWORDS = 'ADD_SEARCH_KEYWORDS';
export const REMOVE_SEARCH_KEYWORDS = 'REMOVE_SEARCH_KEYWORDS';
export const CLEAR_SEARCH_KEYWORDS = 'CLEAR_SEARCH_KEYWORDS';

export const CHANGE_KEYWORD_SUGGESTIONS_SEARCH_TEXT = 'CHANGE_KEYWORD_SUGGESTIONS_SEARCH_TEXT';
export const SET_KEYWORD_SUGGESTIONS_LOADING = 'SET_KEYWORD_SUGGESTIONS_LOADING';
export const LOAD_KEYWORD_SUGGESTIONS = 'LOAD_KEYWORD_SUGGESTIONS';
export const KEYWORD_SUGGESTIONS_LOADING_FAILED = 'KEYWORD_SUGGESTIONS_LOADING_FAILED';

export const OPEN_KEYWORD_SUGGESTIONS_SCREEN = 'OPEN_KEYWORD_SUGGESTIONS_SCREEN';
export const OPEN_SEARCH_FILTER_DRAWER = 'OPEN_SEARCH_FILTER_DRAWER'

export const TOGGLE_SETTING = 'TOGGLE_SETTING';
export const RESET_SORT_AND_FILTER_SETTINGS = 'RESET_SORT_AND_FILTER_SETTINGS';

export const OPEN_NOT_SUBSCRIBED_MODAL = 'OPEN_NOT_SUBSCRIBED_MODAL';
export const CLOSE_NOT_SUBSCRIBED_MODAL = 'CLOSE_NOT_SUBSCRIBED_MODAL';

export const SET_ENTRY_POINT = 'SET_ENTRY_POINT';

export const OPEN_LOADING_MODAL = 'OPEN_LOADING_MODAL';
export const CLOSE_LOADING_MODAL = 'CLOSE_LOADING_MODAL';
export const DO_NOTHING = 'DO_NOTHING';

export const PUSH_HISTORY_ITEM = 'ADD_HISTORY_ITEM';
export const POP_HISTORY_ITEM = 'REMOVE_HISTORY_ITEM';
export const CLEAR_ITEM_HISTORY = 'CLEAR_ITEM_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';

export const LOAD_WHISPERS_OF_THE_DAY = 'LOAD_WHISPERS_OF_THE_DAY';
export const WHISPERS_OF_THE_DAY_LOADING = 'WHISPERS_OF_THE_DAY_LOADING';
export const WHISPERS_OF_THE_DAY_LOADING_FAILED = 'WHISPERS_OF_THE_DAY_LOADING_FAILED';