export const SET_MASTER_CLASS_FINISHED_DATE =
    'app/masterclasses/SET_FINISH_DATE';
export const SET_LOADING = 'app/masterclasses/LOADING';
export const SET_MASTERCLASS_CONTINUE_BUTTON_ENABLED =
    'app/masterclasses/SET_MASTERCLASS_CONTINUE_BUTTON_ENABLED';
export const SET_UI_STATE = 'app/masterclasses/SET_UI_STATE';
export const SET_MASTERCLASS_CONTINUE_BUTTON_VISIBILITY =
    'app/masterclasses/SET_MASTERCLASS_CONTINUE_BUTTON_VISIBILITY';
export const SET_MASTERCLASS_HOME_BUTTON_VISIBILITY =
    'app/masterclasses/SET_MASTERCLASS_HOME_BUTTON_VISIBILITY';
export const SET_MASTERCLASS_HOME_BUTTON_ENABLED =
    'app/masterclasses/SET_MASTERCLASS_HOME_BUTTON_ENABLED';
