export const SET_HEARTS_SPOTS_LOCATION_DETAILS =
    'app/heartSpotsSettings/SET_HEARTS_SPOTS_LOCATION_DETAILS';
export const SET_HEARTS_SPOTS_CURRENT_LOCATION_COORDINATES =
    'app/heartSpotsSettings/SET_HEARTS_SPOTS_CURRENT_LOCATION_COORDINATES';
export const CLEAR_HEARTS_SPOTS_CURRENT_LOCATION_COORDINATES =
    'app/heartSpotsSettings/CLEAR_HEARTS_SPOTS_CURRENT_LOCATION_COORDINATES';
export const SET_HEARTS_SPOTS_LOCATION_STATUS =
    'app/heartSpotsSettings/SET_HEARTS_SPOTS_LOCATION_STATUS';
