export const SITTING_DETAILS_CONTAINER_TYPE = {
    ADD_OFFLINE_SITTING_DETAILS: 'ADD_OFFLINE_SITTING_DETAILS',
    SEEKER_SELECTION_COMPONENT: 'SEEKER_SELECTION_COMPONENT',
    SEEKER_BARCODE_SCANNED_RESULT: 'SEEKER_BARCODE_SCANNED_RESULT',
    SEEKER_SEARCH_RESULT: 'SEEKER_SEARCH_RESULT',
    SELECTED_SEEKERS: 'SELECTED_SEEKERS',
};
