export const LeftNavbarItem = {
    backButton: 'BACK_BUTTON'
} 

export const RightNavbarItem = {
    settingsButton: 'SETTINGS_BUTTON',
    bookmarkButton: 'BOOKMARK_BUTTON',
    searchButton: 'SEARCH_BUTTON',
    themeSettingsButton: 'THEME_SETTINGS_BUTTON'
}

export const CenterNavbarItem = {
    titleText: 'TITLE_TEXT',
    breadCrumb: 'BREAD_CRUMB'
}

export const NavBarType = {
    SELECT_SCREEN_NAVBAR: 'SELECT_SCREEN_NAVBAR',
    DOCUMENT_DETAIL_NAVBAR: 'DOCUMENT_DETAIL_NAVBAR',
    INITIAL_NAVBAR: 'INITIAL_NAVBAR',
    COLLECTION_DOCUMENT_SUGGESTIONS_MODAL_NAVBAR: 'COLLECTION_DOCUMENT_SUGGESTIONS_MODAL_NAVBAR',
    SEARCH_SCREEN_NAVBAR: 'SEARCH_SCREEN_NAVBAR',
    BOOKS_LIST_NAVBAR: 'BOOKS_LIST_SCREEN_NAVBAR',
    WHISPERS_LIST_NAVBAR: 'WHISPERS_LIST_NAVBAR',
    WHISPER_A_DAY_NAVBAR: 'WHISPER_A_DAY_NAVBAR'
}