export const NUNITO_FONT_THEME = 'NUNITO_FONT_THEME';
export const SMALL_SIZE_THEME = 'SMALL_SIZE_THEME';
export const MEDIUM_SIZE_THEME = 'MEDIUM_SIZE_THEME';
export const LARGE_SIZE_THEME = 'LARGE_SIZE_THEME';
export const LIGHT_COLOR_THEME = 'LIGHT_COLOR_THEME';
export const DARK_COLOR_THEME = 'DARK_COLOR_THEME';