export const PRECEPTOR_MEDITATION_ANIMATION_OPTIONS = {
    CONNECTED_TO_SESSION_BUT_NOT_YET_STARTED:
        'CONNECTED_TO_SESSION_BUT_NOT_YET_STARTED',
    PRECEPTOR_SESSION_IN_PROGRESS: 'PRECEPTOR_SESSION_IN_PROGRESS',
};
