export const COMPLETED_INTRO_SITTINGS = 'COMPLETED_INTRO_SITTINGS';
export const COMPLETED_INTRO_SITTINGS_WITH_DAAJI =
    'COMPLETED_INTRO_SITTINGS_WITH_DAAJI';
export const NOT_COMPLETED_INTRO_SITTINGS = 'NOT_COMPLETED_INTO_SITTINGS';
