name: UT-and-lint
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  workflow_dispatch:
    inputs:
      git-ref:
        description: branch (optional)
        required: false
jobs:
  run_lint_and_ut:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name : Setup Node version
        uses: actions/setup-node@v2
        with:
           node-version: '12.18.3'    
      - name: Install npm dependencies
        if: ${{ failure() || success() }}
        run: |
          npm install
      - name: Code Linting Step
        if: ${{ failure() || success() }}
        run: |
          npm run-script lint
      - name: Unit Test Step
        if: ${{ failure() || success() }}
        run: |
          npm run-script test
